version: "3.7"
services:
    cells:
        image: pydio/cells:latest
        restart: unless-stopped
        ports: ["8082:8080"]
        environment:
            - CELLS_SITE_EXTERNAL=https://drive.arunprajapati.com.np
            - CELLS_SITE_NO_TLS=1
        volumes:
            - /cells:/var/cells

    mysql:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
            MYSQL_DATABASE: cells
            MYSQL_USER: pydio
            MYSQL_PASSWORD: P@ssw0rd
            MYSQL_TCP_PORT: 3307
        command:
            [
                mysqld,
                --character-set-server=utf8mb4,
                --collation-server=utf8mb4_unicode_ci,
            ]
        volumes:
            - ./mysqldir:/var/lib/mysql

volumes:
    data: {}
    cellsdir: {}
    mysqldir: {}
