version: "3"
services:
    flame:
        image: pawelmalak/flame
        restart: always
        ports:
            - "5005:5005"
        volumes:
            - ./:/app/data
        environment:
            - PASSWORD=arun1234
