version: "3"
services:
    mediatracker:
        container_name: mediatracker
        ports:
            - 7481:7481
        volumes:
            - ./.config/mediatracker/data:/storage
            - assetsVolume:/assets
        environment:
            SERVER_LANG: en
            TMDB_LANG: en
            AUDIBLE_LANG: us
            TZ: Europe/London
        image: bonukai/mediatracker:latest

volumes:
    assetsVolume: null
