version: "3"
services:
    stirling-pdf:
        image: frooodle/s-pdf:latest
        container_name: stirling-pdf
        restart: always
        ports:
            - "8083:8080"
        volumes:
            - ../../stirling-pdf/trainingData:/usr/share/tesseract-ocr/4.00/tessdata
            - ./configs:/configs
            - ./customFiles:/customFiles/
        environment:
            - DOCKER_ENABLE_SECURITY=false
