version: "3.3"
x-environment: &environment
    environment:
        # The url of your Formbricks instance used in the admin panel
        WEBAPP_URL: "https://arunprajapati.com.np"

        # PostgreSQL DB for Formbricks to connect to
        DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/formbricks?schema=public"

        # Uncomment to enable a dedicated connection pool for Prisma using Prisma Data Proxy
        # Cold boots will be faster and you'll be able to scale your DB independently of your app.
        # @see https://www.prisma.io/docs/data-platform/data-proxy/use-data-proxy
        # PRISMA_GENERATE_DATAPROXY: true
        PRISMA_GENERATE_DATAPROXY:

        # NextJS Auth
        # @see: https://next-auth.js.org/configuration/options#nextauth_secret
        # You can use: e5uo5wrpwNlEwBxHZtEwpYl1xpeiU03I46xWU72rUA0= to generate one
        NEXTAUTH_SECRET: AHiCatnwZXiwaouEMOYKFupAY0RdUUmB

        # Set this to your public-facing URL, e.g., https://example.com
        # You do not need the NEXTAUTH_URL environment variable in Vercel.
        NEXTAUTH_URL: "https://arunprajapati.com.np"

        # PostgreSQL password
        POSTGRES_PASSWORD: postgres

        # Email configuration

services:
    postgres:
        restart: always
        image: postgres:15-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        <<: *environment

    formbricks:
        restart: always
        image: formbricks/formbricks:latest
        depends_on:
            - postgres
        labels:
            - "traefik.enable=true" # Enable Traefik for this service
            - "traefik.http.routers.formbricks.rule=Host(`form.arunprajapati.com.np`)" # Replace your_domain_name with your actual domain or IP
            - "traefik.http.routers.formbricks.entrypoints=websecure" # Use the websecure entrypoint (port 443 with TLS)
            - "traefik.http.services.formbricks.loadbalancer.server.port=3000" # Forward traffic to Formbricks on port 3000
        <<: *environment

    traefik:
        image: "traefik:v2.7"
        restart: always
        container_name: "traefik"
        depends_on:
            - formbricks
        ports:
            - "80:80"
            - "443:443"
            - "8081:8080"
        volumes:
            - ./traefik.yaml:/traefik.yaml
            - ./acme.json:/acme.json
            - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    postgres:
        driver: local
